### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Maanpreet** [we45/orchestron-community#1]
So first of all thanks for this tool. I followed doc from here https://we45devteam.atlassian.net/wiki/spaces/OR/pages/430866437/Installation+and+Deployment and everything seems to be working from docker prospective but I can't login to console (localhost:80). I'm using same admin username and password specified in docker file. Any help regarding where to see login logs ?

**Comment by tilaktwe45** [comment]
Hi Manpreet, 
we have fixed the issue, please check now and let us know if you need any help.

**Comment by Maanpreet** [comment]
Thanks for closing above issue. I was able to login to Tool and it seems nice. Now I'm experiencing anther  issue, there is no option to create Webhook under webhooks pages. Help is appreciated

**Comment by PavitraRaj** [comment]
Hi ,
I am facing similar issue in login screen.
Can you please let me know if the issue is resolved in master version or sprint version of github code.
Thanks,
Pavitra
